core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from school_menu.views import health_check

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("health/", health_check, name="health_check"),
    path("", include("school_menu.urls")),
    path("contacts/", include("contacts.urls")),
    path("users/", include("users.urls")),
    path("notifications/", include("notifications.urls")),
    path(
        "offline/",
        TemplateView.as_view(template_name="offline.html"),
        name="offline",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include("pwa.urls")),
    path("webpush/", include("webpush.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

school_menu/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "school_menu"

urlpatterns = [
    path("", views.index, name="index"),
    path("settings/<int:pk>/", views.settings_view, name="settings"),
    path("school_list", views.school_list, name="school_list"),
    path(
        "get-menu/<int:school_id>/<int:week>/<int:day>/<str:meal_type>/",
        views.get_menu,
        name="get_menu",
    ),
    path("info", TemplateView.as_view(template_name="pages/info.html"), name="info"),
    path(
        "privacy",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
    path("help", TemplateView.as_view(template_name="pages/help.html"), name="help"),
    path("json/schools/", views.get_schools_json_list, name="get_schools_json_list"),
    path(
        "json/menu/<slug:slug>/",
        views.get_school_json_menu,
        name="get_school_json_menu",
    ),
    path("menu/<slug:slug>/", views.school_menu, name="school_menu"),
    path(
        "menu/<int:school_id>/<int:week>/<int:season>/<str:meal_type>/",
        views.create_weekly_menu,
        name="create_weekly_menu",
    ),
    path(
        "export/<int:school_id>/<int:season>/<str:meal_type>/",
        views.export_menu,
        name="export_menu",
    ),
]

htmx_urlpatterns = [
    path("school/", views.school_view, name="school_view"),
    path("school/create/", views.school_create, name="school_create"),
    path("school/update/", views.school_update, name="school_update"),
    path("school/delete/", views.school_delete, name="school_delete"),
    path(
        "menu/<int:school_id>/<str:meal_type>/upload/",
        views.upload_menu,
        name="upload_menu",
    ),
    path(
        "menu/<int:school_id>/<str:meal_type>/annual/upload/",
        views.upload_annual_menu,
        name="upload_annual_menu",
    ),
    path("settings/<int:pk>/menu/", views.menu_settings_partial, name="menu_settings"),
    path("settings/school/", views.school_settings_partial, name="school_settings"),
    path("search-schools/", views.search_schools, name="search_schools"),
    path(
        "export-modal/<int:school_id>/<str:meal_type>/",
        views.export_modal_view,
        name="export_modal",
    ),
    path("report-count/", views.menu_report_count, name="menu_report_count"),
]

urlpatterns += htmx_urlpatterns

school_menu/views.py
from datetime import date, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.db import connection
from django.db.models import Q
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.response import HttpResponse, TemplateResponse
from django.urls import reverse
from django.views.decorators.cache import cache_page
from django.views.decorators.http import require_http_methods
from tablib import Dataset
from tablib.exceptions import InvalidDimensions

from contacts.models import MenuReport
from notifications.tasks import _is_school_in_session
from school_menu.cache import (
    get_cached_or_query,
    invalidate_meal_cache,
    invalidate_school_cache,
)
from school_menu.forms import (
    DetailedMealForm,
    SchoolForm,
    SimpleMealForm,
    UploadAnnualMenuForm,
    UploadMenuForm,
)
from school_menu.models import AnnualMeal, DetailedMeal, Meal, School, SimpleMeal
from school_menu.resources import (
    AnnualMenuExportResource,
    AnnualMenuResource,
    DetailedMealExportResource,
    DetailedMealResource,
    SimpleMealExportResource,
    SimpleMealResource,
)
from school_menu.serializers import (
    AnnualMealSerializer,
    DetailedMealSerializer,
    SchoolSerializer,
    SimpleMealSerializer,
)
from school_menu.utils import (
    build_types_menu,
    calculate_week,
    detect_csv_format,
    fill_missing_dates,
    get_adjusted_year,
    get_alt_menu,
    get_current_date,
    get_meals,
    get_meals_for_annual_menu,
    get_notifications_status,
    get_season,
    get_user,
    validate_annual_dataset,
    validate_dataset,
)


def index(request):
    context = {}
    if request.user.is_authenticated:
        try:
            school = School.objects.get(user=request.user)
        except School.DoesNotExist:
            school = None
            return redirect(reverse("school_menu:settings", args=[request.user.pk]))
        current_week, adjusted_day = get_current_date()
        bias = school.week_bias
        adjusted_week = calculate_week(current_week, bias)
        season = get_season(school)
        alt_menu = get_alt_menu(school.user)
        meal_type = "S"
        if not _is_school_in_session(school, datetime.now()):
            context = {
                "not_in_session": True,
                "start_day": school.start_day,
                "start_month": school.start_month,
                "school": school,
            }
            return render(request, "index.html", context)
        if school.annual_menu:
            weekly_meals, meals_for_today = get_meals_for_annual_menu(school)
            types_menu = build_types_menu(weekly_meals, school)
        else:
            weekly_meals, meals_for_today = get_meals(
                school, season, adjusted_week, adjusted_day
            )
            types_menu = build_types_menu(weekly_meals, school, adjusted_week, season)

        # Filter meals by type using list comprehension (weekly_meals is a list, not QuerySet)
        weekly_meals = [m for m in weekly_meals if m.type == meal_type]

        # Get today's meal for the selected type
        try:
            meal_for_today = next(m for m in meals_for_today if m.type == meal_type)
        except StopIteration:
            meal_for_today = None

        context = {
            "school": school,
            "meal": meal_for_today,
            "weekly_meals": weekly_meals,
            "week": adjusted_week,
            "day": adjusted_day,
            "year": datetime.now().year,
            "alt_menu": alt_menu,
            "types_menu": types_menu,
        }
    return render(request, "index.html", context)


def school_menu(request, slug, meal_type="S"):
    """Return school menu for the given school"""
    school = get_object_or_404(School.objects.select_related("user"), slug=slug)
    pk = request.session.get("anon_notification_pk")
    notifications_status = get_notifications_status(pk, school)
    if not school.is_published:
        return render(request, "school-menu.html", {"not_published": True})
    if not _is_school_in_session(school, datetime.now()):
        context = {
            "not_in_session": True,
            "start_day": school.start_day,
            "start_month": school.start_month,
            "school": school,
        }
        return render(request, "school-menu.html", context)
    current_week, adjusted_day = get_current_date()
    bias = school.week_bias
    adjusted_week = calculate_week(current_week, bias)
    season = get_season(school)
    alt_menu = get_alt_menu(school.user)
    if school.annual_menu:
        weekly_meals, meals_for_today = get_meals_for_annual_menu(school)
        types_menu = build_types_menu(weekly_meals, school)
    else:
        weekly_meals, meals_for_today = get_meals(
            school, season, adjusted_week, adjusted_day
        )
        types_menu = build_types_menu(weekly_meals, school, adjusted_week, season)

    year = get_adjusted_year()

    # Filter meals by type using list comprehension (weekly_meals is a list, not QuerySet)
    weekly_meals = [m for m in weekly_meals if m.type == meal_type]

    # Get today's meal for the selected type
    try:
        meal_for_today = next(m for m in meals_for_today if m.type == meal_type)
    except StopIteration:
        meal_for_today = None

    context = {
        "school": school,
        "meal": meal_for_today,
        "weekly_meals": weekly_meals,
        "week": adjusted_week,
        "day": adjusted_day,
        "year": year,
        "alt_menu": alt_menu,
        "types_menu": types_menu,
        "notifications_status": notifications_status,
    }
    return render(request, "school-menu.html", context)


def get_menu(request, school_id, week, day, meal_type):
    """get menu for the given school, day, week and type"""
    school = get_object_or_404(School.objects.select_related("user"), pk=school_id)
    pk = request.session.get("anon_notification_pk")
    notifications_status = get_notifications_status(pk, school)
    season = get_season(school)
    year = get_adjusted_year()
    alt_menu = get_alt_menu(school.user)
    if school.annual_menu:
        weekly_meals, meals_for_today = get_meals_for_annual_menu(school)
        types_menu = build_types_menu(weekly_meals, school)
    else:
        weekly_meals, meals_for_today = get_meals(school, season, week, day)
        types_menu = build_types_menu(weekly_meals, school, week, season)

    # Filter meals by type using list comprehension (weekly_meals is a list, not QuerySet)
    weekly_meals = [m for m in weekly_meals if m.type == meal_type]

    # Get meal for the specified day and type
    try:
        meal_for_today = next(m for m in weekly_meals if m.day == day)
    except StopIteration:
        meal_for_today = None

    context = {
        "school": school,
        "meal": meal_for_today,
        "weekly_meals": weekly_meals,
        "week": week,
        "day": day,
        "type": meal_type,
        "year": year,
        "alt_menu": alt_menu,
        "types_menu": types_menu,
        "notifications_status": notifications_status,
    }
    return render(request, "partials/_menu.html", context)


@require_http_methods(["GET"])
@cache_page(86400, key_prefix="schools_json")
def get_schools_json_list(request):
    schools = School.objects.filter(is_published=True)
    serializer = SchoolSerializer(schools, many=True)
    return JsonResponse(serializer.data, safe=False)


@require_http_methods(["GET"])
@cache_page(86400, key_prefix="json_api")
def get_school_json_menu(request, slug):
    school = get_object_or_404(School, slug=slug)
    current_week, adjusted_day = get_current_date()
    bias = school.week_bias
    adjusted_week = calculate_week(current_week, bias)
    season = get_season(school)
    if school.annual_menu:
        weekly_meals, meals_for_today = get_meals_for_annual_menu(school)
        serializer = AnnualMealSerializer(weekly_meals, many=True)
    else:
        if school.menu_type == School.Types.SIMPLE:
            weekly_meals = SimpleMeal.objects.filter(
                school=school, week=adjusted_week, season=season
            ).order_by("day")
            serializer = SimpleMealSerializer(weekly_meals, many=True)
        else:
            weekly_meals = DetailedMeal.objects.filter(
                school=school, week=adjusted_week, season=season
            ).order_by("day")
            serializer = DetailedMealSerializer(weekly_meals, many=True)
    meals = list(serializer.data)
    data = {"current_day": adjusted_day, "meals": meals}
    return JsonResponse(data, safe=False)


@login_required
def settings_view(request, pk):
    """Get the settings page"""
    user, alt_menu = get_user(pk)
    active_menu = request.session.get("active_menu", "S")
    menu_label_dict = dict(Meal.Types.choices)
    menu_label = menu_label_dict.get(active_menu)
    report_count = MenuReport.objects.filter(receiver=user).count()
    context = {
        "user": user,
        "alt_menu": alt_menu,
        "menu_label": menu_label,
        "active_menu": active_menu,
        "report_count": report_count,
    }
    return render(request, "settings.html", context)


@login_required
def menu_report_count(request):
    user = request.user
    report_count = MenuReport.objects.filter(receiver=user).count()
    return render(
        request,
        "partials/_settings_account.html#menu_report",
        {"report_count": report_count},
    )


@login_required
def menu_settings_partial(request, pk):
    """ " Get the menu partial of the settings page when reloaded after a change via htmx"""
    user, alt_menu = get_user(pk)
    active_menu = request.GET.get("active_menu", "S")
    request.session["active_menu"] = active_menu
    menu_label_dict = dict(Meal.Types.choices)

templates/base-simplified.html
{% load pwa static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Mensa Scolastica">
        <meta name="keywords" content="menu scolastico mensa">
        <title>
            {% block page_title %}
                Mensa Scolastica
            {% endblock page_title %}
        </title>
        {% progressive_web_app_meta %}
        {% include 'partials/favicon.html' %}
        <!-- TailwindCSS -->
        <link rel="stylesheet" href="{% static 'css/tailwind.css' %}">
        {% include 'partials/javascript.html' %}
    </head>
    <body>
        <div class="container mx-auto">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/base.html
{% load cookiebanner pwa static %}
<!DOCTYPE html>
<html lang="it">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Mensa Scolastica">
        <meta name="keywords" content="menu scolastico mensa">
        <title>
            {% block page_title %}
                Mensa Scolastica
            {% endblock page_title %}
        </title>
        {% progressive_web_app_meta %}
        {% include 'partials/favicon.html' %}
        <!-- TailwindCSS -->
        <link rel="stylesheet" href="{% static 'css/tailwind.css' %}" />
        {% include 'partials/javascript.html' %}
        {% block add_js %}
        {% endblock add_js %}
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% cookiebanner_modal 'bottom_banner' %}
        <div id="fb-root"></div>
        <script async
                defer
                crossorigin="anonymous"
                src="https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v20.0"
                nonce="6qSLf5Dz"></script>
        {% include 'partials/navbar.html' %}
        {% block content %}
        {% endblock content %}
        {% include 'partials/footer.html' %}
        <!-- Modal -->
        {% include 'partials/modal.html' %}
        <!-- Messages -->
        <div id="messages" class="z-3" hx-boost="true">{% include 'partials/messages.html' %}</div>
    </body>
    <script>
        document.addEventListener('alpine:init', () => {
            // Magic: $tooltip
            Alpine.magic('tooltip', el => message => {
                let instance = tippy(el, { content: message, trigger: 'manual' })

                instance.show()

                setTimeout(() => {
                    instance.hide()

                    setTimeout(() => instance.destroy(), 150)
                }, 2000)
            })

            // Directive: x-tooltip
            Alpine.directive('tooltip', (el, { expression }) => {
                tippy(el, { content: expression })
            })
        })
    </script>
</html>

templates/create-weekly-menu.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="py-8 px-4 mx-auto max-w-screen-lg">
        <h1 class="my-4 text-2xl font-bold tracking-tight text-center md:my-6 md:text-left">Modifica il menu settimanale</h1>
        <form method="post">
            {{ formset.management_form|crispy }}
            <div class="grid grid-cols-1 gap-4 md:grid-cols-2 md:gap-6">
                {% for form in formset %}
                    <div>
                        <h2 class="mb-3 text-xl font-bold text-center md:text-left">{{ form.instance.get_day_display }}</h2>
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% crispy form %}
                    </div>
                {% endfor %}
                <div class="flex flex-col col-span-1 gap-4 md:block md:col-span-2 md:text-right">
                    <a href="{% url 'school_menu:settings' school.user.pk %}"
                       class="w-full md:w-auto btn btn-error md:me-2">Annulla</a>
                    <button type="submit" class="w-full md:w-auto btn btn-primary">Salva</button>
                </div>
            </div>
        </form>
    </section>
{% endblock content %}

templates/export-menu.html
{% load filters heroicons static %}
<div class="modal-content">
    <div class="flex justify-between items-center p-3 pb-4 rounded-t border-b md:p-4 border-base-300">
        <h3 id="download-menu-title"
            data-modal-title
            class="text-xl font-semibold text-base-content">
            Scarica il tuo menu ({{ active_menu|type_label|capfirst }})
        </h3>
        <button type="button"
                class="inline-flex justify-center items-center w-8 h-8 text-sm text-gray-400 bg-transparent rounded-lg hover:text-gray-900 hover:bg-gray-200 ms-auto dark:hover:bg-gray-600 dark:hover:text-white"
                x-on:click="openModal = false">
            {% heroicon_solid 'x-mark' class="size-7" %}
            <span class="sr-only">Close modal</span>
        </button>
    </div>
    <div class="grid gap-y-4 gap-x-8 py-4 px-5 mt-3 {% if summer_meals or winter_meals %}sm:grid-cols-2{% endif %} md:py-8 md:px-6">
        {% if school.annual_menu %}
            {% if annual_meals %}
                <a href="{% url 'school_menu:export_menu' school.id 2 active_menu %}"
                   class="inline-flex items-center btn btn-success dark:btn-soft"
                   download="menu_{{ school.name|cut:' '|lower }}_annuale_{{ active_menu|type_label }}">
                    Menu {{ active_menu|type_label|capfirst }}
                    {% heroicon_solid 'arrow-down-tray' class="size-4 ms-2" %}
                </a>

            {% else %}
                <div class="flex items-center p-2 mb-4 text-center text-red-800 bg-red-50 rounded border border-red-200">
                    {% heroicon_solid 'exclamation-triangle' class="size-5 me-2 lg:me-4" %}
                    <span class="text-sm italic">Non hai ancora inserito nessun pasto nel menu della scuola.</span>
                </div>
            {% endif %}
        {% else %}
            {% if not summer_meals and not winter_meals %}
                <div class="flex items-center p-2 mb-4 text-center text-red-800 bg-red-50 rounded border border-red-200">
                    {% heroicon_solid 'exclamation-triangle' class="size-5 me-2 lg:me-4" %}
                    <span class="text-sm italic">Non hai ancora inserito nessun pasto nel menu della scuola.</span>
                </div>
            {% else %}
                <a href="{% url 'school_menu:export_menu' school.id 2 active_menu %}"
                   class="inline-flex items-center btn btn-success dark:btn-soft"
                   download="menu_{{ school.name|cut:' '|lower }}_inv_{{ active_menu|type_label }}"
                   {% if not winter_meals %}disabled="disabled"{% endif %}>
                    Menu Invernale
                    {% heroicon_solid 'arrow-down-tray' class="size-4 ms-2" %}
                </a>
                <a href="{% url 'school_menu:export_menu' school.id 1 active_menu %}"
                   class="inline-flex items-center btn btn-success dark:btn-soft"
                   download="menu_{{ school.name|cut:' '|lower }}_est_{{ active_menu|type_label }}"
                   {% if not summer_meals %}disabled="disabled"{% endif %}>
                    Menu Estivo
                    {% heroicon_solid 'arrow-down-tray' class="size-4 ms-2" %}
                </a>
            {% endif %}
        {% endif %}
    </div>
</div>

templates/index.html
{% extends 'base.html' %}
{% load partials %}
{% block page_title %}
    Menu Scolastico
{% endblock page_title %}
{% partialdef search-result %}
<div id="school-list"
     class="{% if hidden %}hidden{% endif %} mt-6 p-2 bg-gray-50 border border-gray-100 rounded-md">
    <ul>
        {% if no_schools %}
            <p class="italic font-light text-red-600">Nessuna scuola soddisfa i criteri di ricerca...</p>
        {% else %}
            {% for school in schools %}
                <li class="mb-3">
                    <a class="flex justify-start items-center font-medium text-gray-600 hover:text-green-600 hover:underline underline-offset-2"
                       href="{{ school.get_absolute_url }}">{{ school.name }} ({{ school.city }})</a>
                </li>
            {% endfor %}
        {% endif %}
    </ul>
</div>
{% endpartialdef %}
{% block content %}
<div class="container mx-auto mb-8 max-w-5xl">
    <div class="grid px-4 pt-8 pb-4 mx-auto max-w-7xl lg:gap-8 lg:pt-16 lg:pb-8 xl:gap-0">
        {% if user.is_authenticated %}
            <div class="place-self-center mx-auto">{% include 'partials/_menu.html' %}</div>
        {% else %}
            <div class="place-self-center mx-auto">{% include 'partials/_anon_index.html' %}</div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/offline.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Mensa Scolastica">
        <meta name="keywords" content="menu scolastico mensa">
        <title>Menu Scolastico Offline</title>
        <style>
            html, body {
                height: 100%;
                margin: 0;
                font-family: sans-serif;
                background-color: #f8f9fa;
                color: #989898;
            }
            body {
                display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;
            }
            h1 {
                font-size: 24px;
                margin-top: 0;
            }
        </style>
</head>
<body>
<h1>Non sei connesso a internet al momento. Verifica la tua connessione e ricarica la pagina.</h1>
</body>
</html>

templates/school-list.html
{% extends 'base.html' %}
{% load heroicons partials %}
{% block page_title %}
    Tutte le scuole
{% endblock page_title %}

{% block content %}
<div class="container mx-auto mb-8 max-w-screen-lg">
    <div class="grid px-4 pt-8 pb-4 mx-auto max-w-screen-lg lg:gap-8 lg:pt-16 lg:pb-8 xl:gap-0">
        <h1 class="mb-4 text-2xl font-semibold tracking-tight text-center">Scuole</h1>
        <p class="text-base-content">
            Qui puoi vedere tutte le scuole e i relativi menu creati dai nostri utenti. Non siamo responsabili della correttezza dei menu pubblicati.
        </p>
        <div class="grid grid-cols-1 gap-3 mx-auto max-w-screen-xl md:grid-cols-2 grid-cols">
            <!-- School Search -->
            <div id="search" class="my-4 md:order-last">
                <div class="flex items-center my-4 mx-auto max-w-sm">
                    <label for="simple-search" class="relative input">
                        <span class="sr-only">Cerca scuola o città</span>
                        {% heroicon_outline 'magnifying-glass' class="w-5 h-5 text-primary" %}
                        <input type="search"
                                id="simple-search"
                                name="q"
                                hx-get="{% url 'school_menu:search_schools' %}"
                                hx-swap="outerHTML"
                                hx-trigger="keyup changed delay:1s"
                                hx-target="#school-list"
                                hx-indicator="#spinner"
                                class="grow"
                                placeholder="Cerca scuola o città..."
                                autocomplete="off"
                                required />
                        <span id="spinner"
                                class="absolute top-2 htmx-indicator loading loading-bars text-primary loading-md end-8">
                        </span>
                    </label>
                </div>
            </div>
            <!-- School List -->
            {% partialdef search-result inline %}
            <div id="school-list">
                <ul class="md:mt-6">
                    {% if no_schools %}
                        <p class="italic font-light text-error">Nessuna scuola soddisfa i criteri di ricerca...</p>
                    {% else %}
                        {% for school in schools %}
                            <li class="mb-3">
                                <a class="font-medium hover:underline text-base-content/90 underline-offset-2 hover:text-primary"
                                    href="{{ school.get_absolute_url }}">{{ school.name }} ({{ school.city }})
                                    {% if index %}
                                        {% heroicon_solid 'arrow-right-circle' class="text-primary size-5 ms-2" %}
                                    {% endif %}
                                </a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        {% endpartialdef %}
        </div>
    </div>
</div>
{% endblock content %}

templates/school-menu.html
{% extends 'base.html' %}

{% block page_title %}
    Menu Scolastico
{% endblock page_title %}

{% block content %}
    <div class="grid px-4 pt-8 pb-4 mx-auto max-w-screen-xl lg:gap-8 lg:pt-16 lg:pb-8 xl:gap-0">
        {% if not_published %}
            <div class="place-self-center mx-auto">{% include 'partials/_notpublished.html' %}</div>
        {% else %}
            <div class="place-self-center mx-auto">{% include 'partials/_menu.html' %}</div>
        {% endif %}
    </div>
{% endblock content %}

templates/settings.html
{% extends 'base.html' %}
{% load filters heroicons partials static %}
{% block page_title %}
    Impostazioni
{% endblock page_title %}

{% block content %}
<!-- INFO -->
{% include 'partials/_settings_info.html' %}
<!-- SCHOOL -->
{% partialdef school inline %}
{% include 'partials/_settings_school.html' %}
{% endpartialdef %}
<!-- MENU  -->
{% partialdef menu inline %}
{% include 'partials/_settings_menu.html' %}
{% endpartialdef %}
<!-- ACCOUNT -->
{% include 'partials/_settings_account.html' %}
{% endblock content %}